### ISSUE TITLE
A selection of inaccurate feedback provided by the app

### ISSUE THREAD

**Issue by sofer** [ameliejyc/prereq-check#97] opened 2017-12-08 18:19 UTC
http://prereq-check.herokuapp.com/report?githubPage=https://tanyaba.github.io&fccHandle=tanyaba&cwHandle=tanyaba&ghHandle=tanyaba&submit=GO

> showing as 6 kyu

http://prereq-check.herokuapp.com/report?githubPage=https://github.com/matthausen/Portfolio&fccHandle=matthausen&cwHandle=matthausen&ghHandle=matthausen&submit=GO

> "Codewars: authored 1+ Kata", but it's not true

http://prereq-check.herokuapp.com/report?githubPage=Tova7.github.io&fccHandle=Tova7&cwHandle=Tova7&ghHandle=Tova7&submit=GO

> "8  kyu", but should be 4 kyu

http://prereq-check.herokuapp.com/report?githubPage=https://jamsgra.github.io/&fccHandle=jamsgra&cwHandle=jamsgra&ghHandle=jamsgra&submit=GO

> "Fetching Github commit count failed"

http://prereq-check.herokuapp.com/report?githubPage=https://stephenjukes.github.io/&fccHandle=stephenjukes&cwHandle=dukies_2000&ghHandle=stephenjukes&submit=GO#codewars

> "5 kyu"

http://prereq-check.herokuapp.com/report?githubPage=https://misskatiapunter.github.io/&fccHandle=misskatiapunter&cwHandle=missKatiaPunter&ghHandle=missKatiaPunter&submit=GO

> "4 kyu" but it should be "3 kyu"

http://prereq-check.herokuapp.com/report?githubPage=https://um160.github.io/&fccHandle=Um160&cwHandle=Um160&ghHandle=Um10&submit=GO

> "0 contributions in the last year"
**Response** from @bartbucknill: Unable to replicate - I see '3 contributions', and '3 commits on this project'.

**Comment by Parissai** [comment] 2017-12-18 14:52
Some of the inaccurate feedback can be justified as the app returns JavaScript rank in Codewars which sometimes varies from the overall rank, as people train in more than one language.

**Comment by ameliejyc** [comment] 2018-03-04 17:40
## Codewars bug fixing update

- **No action needed:** The kyu rankings bugs raised can be ignored because we are fetching _just_ the JavaScript kyu level (as opposed to all languages kyu level) and Dan has confirmed this is indeed the piece of information we want to show.

- **Maybe action needed:** The last bug listed related to 'contributions' also doesn't seem to be a bug anymore by Bart's response but is worth digging into a bit to see if we can double check contributions exist.

- **Action needed:** The second bug _"Codewars: authored 1+ Kata", but it's not true"_ appears to occur in the rare cases that a kata was authored but was then retired/deleted/gone for some reason. We're currently checking this **user** endpoint which isn't being updated in these cases:
`https://www.codewars.com/api/v1/users/matthausen`
(shows 1 authored kata)
What we could do as well/or instead is check the **authored kata** endpoint to see if it contains data or is an empty array:
`https://www.codewars.com/api/v1/users/matthausen/code-challenges/authored/`
(shows `data: [ ]`)

**Comment by BartBucknill** [comment] 2018-03-17 13:58
@matthewdking has fixed the authored kata bug. 
We have concluded that the kyu ranking issue is not a bug, and we are unable to replicate the '0 contributions' issue.
Remaining to do on this issue:

- [ ] 'Fetching github commit count failed' occurs frequently but not always. Need to investigate and fix.

- [ ]

**Comment by BartBucknill** [comment] 2018-03-17 14:08
@sofer Tehfetching github commit count failed seems to not be an issue with prereq-check, but with the urls you provided above; they include an unneeded forward slash '/' after the applicants site url.

This is wrong: 
http://prereq-check.herokuapp.com/report?githubPage=https://stephenjukes.github**.io/&fc**cHandle=stephenjukes&cwHandle=dukies_2000&ghHandle=stephenjukes&submit=GO#codewars

It should be this:
http://prereq-check.herokuapp.com/report?githubPage=https://stephenjukes.github**.io&fc**cHandle=stephenjukes&cwHandle=dukies_2000&ghHandle=stephenjukes&submit=GO#codewars

I'm guessing these may have been generated by a script in the google sheet, if so it seems to be that which we should change.

**Comment by BartBucknill** [comment] 2018-03-17 14:08
@sofer can you review these updates and close the issue if your happy?

**Closed** 2018-03-17 14:34 UTC
Labels: bug, priority-1
